Fix logrotate permissions
/vagrant/logs/ is owned by vagrant:vagrant (has to be as it's shared
with the host machine) which results in errors like
  error: skipping "/vagrant/logs/foo.log" because parent directory
  has insecure permissions (It's world writable or writable by group
  which is not "root") Set "su" directive in config file to tell
  logrotate which user/group should be used for rotation.
Ownership of the log directory needs to be specified manually
to avoid that.

Change-Id: I74907dc696e05cb3db23441056e30ade25b73e9c